---
- name: Update-grub
  ansible.builtin.shell: update-grub
  notify: reboot

- name: Update-initramfs
  ansible.builtin.shell: update-initramfs -u
  notify: reboot

- name: Reboot
  ansible.builtin.reboot:

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
