---
- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: true
  notify: Reboot

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: Reboot

- name: Reboot
  ansible.builtin.reboot:

- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted
  async: 5
  poll: 0
  ignore_errors: true

# - name: Restart nginx
#   ansible.builtin.systemd:
#     name: nginx
#     state: restarted
