---
- name: Get ISO images
  ansible.builtin.shell:
    pvesh get /nodes/{{ ansible_facts.hostname }}/storage/{{ storage.name }}/content
    --content iso
    --output-format json
  changed_when: false
  register: existing_iso_files

- name: Update ISO images
  vars:
    iso_names: "{{ storage.isos | map('basename') }}"
    existing_iso_names: 
      "{{ existing_iso_files.stdout | from_json | json_query('[].volid') | map('basename') }}"
  block:
    - debug: var=iso_names
    - debug: var=existing_iso_names

    - name: Download ISO images
      ansible.builtin.shell: >-
        pvesh create /nodes/{{ ansible_facts.hostname }}/storage/{{ storage.name }}/download-url
        --content iso
        --filename {{ iso | basename }}
        --url {{ iso }}
      when: iso | basename not in existing_iso_names
      with_items: "{{ storage.isos }}"
      loop_control:
        loop_var: iso

    - name: Delete ISO images
      ansible.builtin.shell: >-
        pvesh delete /nodes/{{ ansible_facts.hostname }}/storage/{{ storage.name }}/content/{{ iso }}
      when: iso | basename not in iso_names
      with_items: "{{ existing_iso_files.stdout | from_json | json_query('[].volid') }}"
      loop_control:
        loop_var: iso
