---
managed_by_ansible_tag: managed_by_ansible

container_remove_unreferenced: true

container_defaults:
  cores: 1
  memory: 512
  swap: 512
  nesting: true
  onboot: false
  unprivileged: true
  timezone: host
  start: false
  netdev_firewall: true
  nameserver: ''
  searchdomain: ''
