---
switch_to_community_updates_repo: true
disable_no_subscription_prompt: true
install_pve_discord_dark_theme: true
enable_acme: false
install_nginx_proxy: true

managed_by_ansible_tag: managed_by_ansible

vm_iso_remove_unreferenced: true
ct_template_remove_unreferenced: true
vm_remove_unreferenced: true
container_remove_unreferenced: true

vm_defaults:
  bios: ovmf
  cores: 1
  cpu: host
  memory: 512
  onboot: false
  machine: q35
  ostype: l26
  scsihw: virtio-scsi-pci
  sockets: 1
  vga: qxl
  netdev_firewall: true
  netdev_type: virtio
  netdev_bridge: vmbr0

container_defaults:
  cores: 1
  memory: 512
  swap: 512
  nesting: true
  onboot: false
  unprivileged: true
  timezone: host
  start: false
  netdev_firewall: true
  nameserver: ''
  searchdomain: ''
