---
- name: Get existing VMs
  ansible.builtin.shell: pvesh get /nodes/{{ ansible_facts.hostname }}/qemu --output-format json
  register: existing_vms
  changed_when: false

- name: Clone {{ clone.name }} from template {{ clone.template }}
  ansible.builtin.shell: >
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ clone.template }}/clone
    --newid {{ clone.vmid }}
  when: clone.vmid not in existing_vms.stdout | from_json | json_query('[].vmid')
