---
- name: Install nginx using apt
  ansible.builtin.apt:
    pkg: nginx
    state: latest

- name: Remove default nginx config file
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Update nginx config
  ansible.builtin.template:
    src: templates/proxmox.conf.j2
    dest: /etc/nginx/conf.d/proxmox.conf
    backup: true
    mode: 0644
  notify: restart nginx
