---
- ansible.builtin.import_tasks: setup/main.yml
  tags: setup

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- ansible.builtin.import_tasks: storage/main.yml
  tags: storage

- ansible.builtin.import_tasks: templates/main.yml
  tags: templates

- ansible.builtin.import_tasks: vm/main.yml
  tags: vms

- ansible.builtin.import_tasks: containers/main.yml
  tags: containers
