---
- ansible.builtin.import_tasks: switch_to_community_updates_repo.yml
- ansible.builtin.import_tasks: update.yml
- ansible.builtin.import_tasks: disable_subscription_prompt.yml
- ansible.builtin.import_tasks: install_pve_dark_theme.yml
- ansible.builtin.import_tasks: acme/enable_acme.yml
- ansible.builtin.import_tasks: install_nginx.yml

- ansible.builtin.include_tasks: create_template.yml
  with_items: "{{ templates }}"
  loop_control:
    loop_var: template

- ansible.builtin.include_tasks: create_clones.yml
  with_items: "{{ clones }}"
  loop_control:
    loop_var: clone

- ansible.builtin.include_tasks: configure_vms.yml
  with_items: "{{ vms }}"
  loop_control:
    loop_var: vm
