---
- name: Setup Proxmox
  ansible.builtin.import_tasks: setup/main.yml
  tags: setup

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Include networking tasks
  ansible.builtin.import_tasks: networking/main.yml
  tags: networking

- name: Setup storage
  ansible.builtin.import_tasks: storage/main.yml
  tags: storage

- name: Setup templates and isos
  ansible.builtin.import_tasks: templates/main.yml
  tags: templates

- name: Ensure dependencies are installed for cloud-init are installed
  ansible.builtin.import_tasks: setup/main.yml

- name: Create Ubuntu 24.04 VM template
  ansible.builtin.import_tasks: templates/ubuntu-2404.yml
  when: ubuntu_template.enabled | default(false)
  tags: ubuntu_template

- name: Setup VMs
  ansible.builtin.import_tasks: vm/main.yml
  tags: vms

- name: Setup Containers
  ansible.builtin.import_tasks: containers/main.yml
  tags: containers
