---
- name: Setup Proxmox
  ansible.builtin.import_tasks: setup/main.yml
  tags: setup

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup storage
  ansible.builtin.import_tasks: storage/main.yml
  tags: storage

- name: Setup templates and isos
  ansible.builtin.import_tasks: templates/main.yml
  tags: templates

- name: Setup VMs
  ansible.builtin.import_tasks: vm/main.yml
  tags: vms

- name: Setup Containers
  ansible.builtin.import_tasks: containers/main.yml
  tags: containers
