---
- name: Get plugins
  ansible.builtin.shell: pvesh get /cluster/acme/plugins --output-format json
  register: acme_plugins
  changed_when: false

- name: Enable azure DNS plugin
  vars:
    acme_plugin_data: |
      AZUREDNS_SUBSCRIPTIONID={{ acme_plugin_azure_subscriptionid }}
      AZUREDNS_TENANTID={{ acme_plugin_azure_tenantid }}
      AZUREDNS_APPID={{ acme_plugin_azure_appid }}
      AZUREDNS_CLIENTSECRET={{ acme_plugin_azure_clientsecret }}
  ansible.builtin.shell: >
    pvesh create /cluster/acme/plugins
    --id {{ acme_plugin_name }}
    --api azure
    --type {{ acme_plugin_type }}
    --data {{ acme_plugin_data | b64encode }}
  when: "'azure' not in acme_plugins.stdout | from_json | json_query('[].plugin')"
