---
domain: example.com

update_packages: false
debian_version: bookworm # use bullseye for pve 7.x

switch_to_community_updates_repo: true
disable_no_subscription_prompt: true
install_pve_discord_dark_theme: true
enable_acme: false
install_nginx_proxy: true

acme_email: changeme
acme_staging: false
acme_plugin_name: cloudflare
acme_plugin_cloudflare_email: changeme
acme_plugin_cloudflare_token: changeme

# if using Azure dns provider uncomment
# acme_plugin_name: azure
# acme_plugin_azure_appid: changeme
# acme_plugin_azure_clientsecret: changeme
# acme_plugin_azure_subscriptionid: changeme
# acme_plugin_azure_tenantid: changeme

ssh_keys: changeme

pcie_passthrough:
  enable: true
  allow_unsafe_interrupts: false
  ids:
    - 10de:1c30
    - 10de:10f1
  blocklist:
    - nouveau
    - nvidia
    - radeon
    - amdgpu
    - i915

vm_iso_remove_unreferenced: true
ct_template_remove_unreferenced: true
vm_remove_unreferenced: true
container_remove_unreferenced: true

templates:
  9000:
    name: debian-bullseye
    cloud_image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
    storage: local-lvm
  9001:
    name: ubuntu-2204
    cloud_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    storage: local-lvm

storage:
  local:
    isos:
      - https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.4.0-amd64-netinst.iso
    ct_templates:
      - ubuntu-22.04-standard_22.04-1_amd64.tar.zst
      - debian-11-standard_11.3-1_amd64.tar.zst
      - debian-10-turnkey-gitea_16.1-1_amd64.tar.gz

vms:
  100:
    name: new-vm
    cores: 4
    memory: 4096
    storage: local-lvm
    network_devices:
      0:
    disks:
      scsi0:
        size: 50
      scsi1:
        size: 50
    cd_drives:
      ide0:
        iso: debian-11.4.0-amd64-netinst.iso
        storage: local
    snapshots:
      created:

  200:
    template: 9000
    name: k3s-master-001
    cores: 4
    memory: 4096
    onboot: true
    storage: local-lvm
    ci:
      user: rsandor
      ssh_keys: "{{ ssh_keys }}"
    network_devices:
      0:
    ipconfig:
      0:
        ip: "192.168.1.21/24"
        gateway: "192.168.1.1"
    disks:
      scsi0:
        size: 50

  201:
    template: 9000
    name: k3s-node-001
    cores: 4
    memory: 4096
    onboot: true
    storage: local-lvm
    ci:
      user: rsandor
      ssh_keys: "{{ ssh_keys }}"
    network_devices:
      0:
    ipconfig:
      0:
        ip: "192.168.1.22/24"
        gateway: "192.168.1.1"
    disks:
      scsi0:
        size: 50

  202:
    template: 9000
    name: k3s-node-002
    cores: 4
    memory: 4096
    onboot: true
    storage: local-lvm
    ci:
      user: rsandor
      ssh_keys: "{{ ssh_keys }}"
    network_devices:
      0:
    ipconfig:
      0:
        ip: "192.168.1.23/24"
        gateway: "192.168.1.1"
    disks:
      scsi0:
        size: 50

  400:
    template: 9000
    name: debian-test
    cores: 4
    memory: 4096
    storage: local-lvm
    ci:
      user: rsandor
      ssh_keys: "{{ ssh_keys }}"
    network_devices:
      0:
    ipconfig:
      0:
        ip: "192.168.1.31/24"
        gateway: "192.168.1.1"
    disks:
      scsi0:
        size: 50
    snapshots:
      created:

  401:
    template: 9001
    name: ubuntu-server-test
    cores: 4
    memory: 4096
    storage: local-lvm
    ci:
      user: rsandor
      ssh_keys: "{{ ssh_keys }}"
    network_devices:
      0:
    ipconfig:
      0:
        ip: "192.168.1.32/24"
        gateway: "192.168.1.1"
    disks:
      scsi0:
        size: 50
    snapshots:
      created:

containers:
  1001:
    hostname: ubuntu-ct
    password: changeme
    ssh_keys: "{{ ssh_keys }}"
    template:
      storage: local
      name: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
    cores: 4
    memory: 2048
    swap: 2048
    network_devices:
      net0:
        name: eth0
        bridge: vmbr0
        ip: 192.168.1.51/24
        gateway: 192.168.1.1
    rootfs:
      storage: local-lvm
      size: 15
