---
- name: Switch to community APT repo
  ansible.builtin.import_tasks: switch_to_community_updates_repo.yml
  when: switch_to_community_updates_repo

- name: Update Proxmox
  ansible.builtin.import_tasks: update.yml

- name: Disable Proxmox Subscription prompt
  ansible.builtin.import_tasks: disable_subscription_prompt.yml
  when: disable_no_subscription_prompt

- name: Install Dark Theme
  ansible.builtin.import_tasks: install_pve_dark_theme.yml
  when: install_pve_discord_dark_theme

- name: Enable ACME certificate management
  ansible.builtin.import_tasks: acme/enable_acme.yml
  when: enable_acme

- name: Install NGINX
  ansible.builtin.import_tasks: install_nginx.yml
  when: install_nginx_proxy
- ansible.builtin.import_tasks: gpu_passthrough.yml

