---
- name: Switch to community APT repo
  ansible.builtin.import_tasks: switch_to_community_updates_repo.yml
  when: switch_to_community_updates_repo

- name: Update Proxmox
  ansible.builtin.import_tasks: update.yml

- name: Disable Proxmox Subscription prompt
  ansible.builtin.import_tasks: disable_subscription_prompt.yml
  when: disable_no_subscription_prompt

- name: Install Dark Theme
  ansible.builtin.import_tasks: install_pve_dark_theme.yml
  when: install_pve_discord_dark_theme

- name: Enable ACME certificate management
  ansible.builtin.import_tasks: acme/enable_acme.yml
  when: enable_acme

- name: Install NGINX
  ansible.builtin.import_tasks: install_nginx.yml
  when: install_nginx_proxy

- name: Setup GPU passthrough
  ansible.builtin.import_tasks: pcie_passthrough.yml
  when: pcie_passthrough.enable

# ansible-galaxy collection install community.general
- name: Create or update Cloudflare DNS record with private IP
  when: cloudflare_enabled | default(false)
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_zone }}"
    record: "{{ cloudflare_record_name }}"
    type: "{{ cloudflare_record_type }}"
    value: "{{ cloudflare_record_ip }}"
    ttl: "{{ cloudflare_ttl }}"
    proxied: "{{ cloudflare_proxy }}"
    api_token: "{{ cloudflare_api_token }}"
  delegate_to: localhost
  vars:
    ansible_connection: local
    ansible_become: false
    ansible_python_interpreter: /usr/bin/python3
