---
- name: Container {{ ct.key }}> Create new container
  vars:
    netcfg: "{% for net in ct.value.network_devices | default({}) | dict2items %}
      --net{{ net.key }} name={{ net.value.name }},\
      bridge={{ net.value.bridge }},\
      firewall={{ net.value.firewall | default(container_defaults.netdev_firewall) | ternary(1, 0) }},\
      ip={{ net.value.ip }},\
      gw={{ net.value.gateway }}\
      {{ ',tag=' + net.value.vlan_tag | string if net.value.vlan_tag is defined else '' }}
      {% endfor %}"
    container_tags: "{{ '--tags ' + (ct.value.tags | default([]) + [managed_by_ansible_tag]) | join(',') }}"
    nameserver: "{{ '--nameserver ' + ct.value.nameserver if ct.value.nameserver is defined else '' }}"
    searchdomain: "{{ '--searchdomain ' + ct.value.searchdomain if ct.value.searchdomain is defined else '' }}"
  ansible.builtin.command: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/lxc
    --vmid {{ ct.key }}
    --ostemplate {{ ct.value.template.storage }}:vztmpl/{{ ct.value.template.name }}
    --hostname {{ ct.value.hostname }}
    --password {{ ct.value.password }}
    --ssh-public-keys "{{ ct.value.ssh_keys }}"
    --cores {{ ct.value.cores | default(container_defaults.cores) }}
    --memory {{ ct.value.memory | default(container_defaults.memory) }}
    --swap {{ ct.value.swap | default(container_defaults.swap) }}
    --rootfs {{ ct.value.rootfs.storage }}:{{ ct.value.rootfs.size }}
    --features nesting={{ ct.value.nesting | default(container_defaults.nesting) | ternary(1, 0) }}
    --onboot {{ ct.value.onboot | default(container_defaults.onboot) | ternary(1, 0) }}
    --unprivileged {{ ct.value.unprivileged | default(container_defaults.unprivileged) | ternary(1, 0) }}
    --timezone {{ ct.value.timezone | default(container_defaults.timezone) }}
    --start {{ ct.value.start | default(container_defaults.start) | ternary(1, 0) }}
    {{ nameserver }}
    {{ searchdomain }}
    {{ container_tags }}
    {{ netcfg }}
  changed_when: true
