---
- name: Clone from template VM-{{ vm.key }}
  ansible.builtin.import_tasks: create_vm_clone.yml
  when: vm.value.template is defined

- name: Create standalone VM-{{ vm.key }}
  ansible.builtin.import_tasks: create_vm_standalone.yml
  when: vm.value.template is not defined
