---
- name: Clone from template
  ansible.builtin.shell: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.template }}/clone
    --newid {{ vm.vmid }}
  when: vm.template is defined
  changed_when: true

- name: Create standalone VM
  ansible.builtin.shell: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu --vmid {{ vm.vmid }}
  when: vm.template is not defined
  changed_when: true
