---
- name: Get existing VMs
  ansible.builtin.shell: pvesh get /nodes/{{ ansible_facts.hostname }}/qemu --output-format json
  register: existing_vms
  changed_when: false

- name: Create VM if missing
  ansible.builtin.include_tasks: create_vm.yml
  when: vm.vmid not in existing_vms.stdout | from_json | json_query('[].vmid')
  with_items: "{{ vms }}"
  loop_control:
    loop_var: vm

- ansible.builtin.include_tasks: configure_vm.yml
  with_items: "{{ vms }}"
  loop_control:
    loop_var: vm
