---
- name: Setup network device
  ansible.builtin.shell: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.vmid }}/config
    --{{ netdev.id }} {{ type_and_mac }},{{ bridge }},{{ firewall }},{{ vlan_tag }}
  when: >-
    type_and_mac not in current_config or
    bridge not in current_config_parts or
    firewall not in current_config_parts or
    (vlan_tag | length > 0 and vlan_tag not in current_config_parts or
    vlan_tag | length == 0 and 'tag=' in current_config)
  vars:
    current_config: "{{ existing_vm_config | json_query(netdev.id) }}"
    current_config_parts: "{{ current_config | split(',') }}"
    type_and_mac: "{{ netdev.type }}{{ '' if netdev.mac is not defined else '=' + netdev.mac | string }}"
    bridge: "bridge={{ netdev.bridge }}"
    firewall: "firewall={{ netdev.firewall | default(true) | ternary('1', '0') }}"
    vlan_tag: "{{ '' if netdev.vlan_tag is not defined else 'tag=' + netdev.vlan_tag | string }}"
