---
- name: VM {{ vm.key }} > Get pending updates for VM
  ansible.builtin.shell: >-
    pvesh get /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/pending
    --output-format json
  changed_when: false
  register: pending_changes_response

- name: Reboot VM if changes pending
  vars:
    changes_pending: "{{ pending_changes_response.stdout | from_json | \
      json_query('[].[pending, delete] | []') | length > 0 }}"
  ansible.builtin.shell: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/status/reboot
    --timeout {{ vm_restart_timeout }}
  when: changes_pending
