---
- name: Resize VM storage
  ansible.builtin.shell: >-
    pvesh set /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.vmid }}/resize
    --disk {{ storage.disk }}
    --size {{ storage.size }}
  changed_when: true
  when: existing_storage_config | length > 0 and 'size=' + storage.size not in existing_storage_config
  vars:
    existing_storage_config: "{{ existing_vm_config | json_query(storage.disk) }}"

- name: Create VM storage
  when: existing_storage_config | length == 0
  vars:
    existing_storage_config: "{{ existing_vm_config | json_query(storage.disk) }}"
  block:
    - name: Validate name and location are defined
      ansible.builtin.fail:
        msg: "To create storage for VM {{ vm.vmid }}, 'name' and 'location' vars are required on the storage config."
      when: storage.location is not defined or storage.name is not defined

    - name: Create storage for VM
      ansible.builtin.shell: >-
        pvesh create /nodes/{{ ansible_facts.hostname }}/storage/{{ storage.location }}/content
        --vmid {{ vm.vmid }}
        --filename vm-{{ vm.vmid }}-{{ storage.name }}
        --size {{ storage.size }}
      changed_when: true

    - name: Add storage to VM
      ansible.builtin.shell: >-
        pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.vmid }}/config
        --{{ storage.disk }} {{ storage.location }}:vm-{{ vm.vmid }}-{{ storage.name }}
      changed_when: true
