---
- name: Get existing VM configuration VM-{{ vm.key }}
  ansible.builtin.command: >-
    pvesh get /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/config --output-format json
  register: vm_config_response
  changed_when: false

- name: Update VM configuration VM-{{ vm.key }}
  vars:
    vm_config: "{{ vm_config_response.stdout | from_json }}"
  block:
    - name: Update VM configuration
      ansible.builtin.import_tasks: update_vm_config.yml
    - name: Update VM network devices
      ansible.builtin.import_tasks: update_network_devices.yml
    - name: Update VM disks
      ansible.builtin.import_tasks: update_disks.yml
    - name: Update VM cd drives
      ansible.builtin.import_tasks: update_cd_drives.yml
    - name: Reboot VM if updated
      ansible.builtin.import_tasks: reboot_updated_vm.yml
    - name: Update VM snapshots
      ansible.builtin.import_tasks: update_snapshots.yml
