---
# Simple playbook to list available CT images from Proxmox's database
#
# Example:
#
# To list all images
# ansible-playbook playbooks/list_ct_images.yml -i inventories/sample/hosts.yml
#
# To list images containing a keyword
# ansible-playbook playbooks/list_ct_images.yml -i inventories/sample/hosts.yml -e "search=ubuntu"

- hosts: all

  name: List available CT images

  vars:
    search:

  tasks:
    - name: Get available CT images
      ansible.builtin.shell: >-
        pvesh get /nodes/{{ ansible_facts.hostname }}/aplinfo --output-format json
      changed_when: false
      register: aplinfo

    - name: Print available CT images
      ansible.builtin.debug:
        msg: "{{ available_ct_images }}"
      vars:
        search_query: "[?contains(template, '{{ search }}')].template"
        available_ct_images: "{{ aplinfo.stdout | from_json | json_query(search_query) }}"
